


/*
SELECT * FROM TABELA_DE_VENDEDORES WHERE YEAR(DATA_ADMISSAO) < 2016 AND DE_FERIAS = 1;
SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;
SELECT * FROM tbproduto WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;
SELECT * FROM tbcliente WHERE IDADE >= 18 AND IDADE <=22 AND SEXO = 'M';
SELECT * FROM tbcliente WHERE CIDADE = 'RIO DE JANEIRO' OR BAIRRO = 'JARDINS';

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO = '1995-01-13';
SELECT * FROM tbcliente WHERE DATA_NASCIMENTO > '1995-01-13';
SELECT * FROM tbcliente WHERE DATA_NASCIMENTO <= '1995-01-13';
SELECT * FROM tbcliente WHERE year(DATA_NASCIMENTO) = 1995;
SELECT * FROM tbcliente WHERE month(DATA_NASCIMENTO) = 10;
SELECT * FROM tabela_de_vendedores WHERE YEAR(DATA_ADMISSAO) >= 2016;

SELECT * FROM tbcliente WHERE IDADE = 22;
SELECT * FROM tbcliente WHERE IDADE > 22; 
SELECT * FROM tbcliente WHERE IDADE < 22; 
SELECT * FROM tbcliente WHERE IDADE <= 22; 
SELECT * FROM tbcliente WHERE IDADE <> 22; 
SELECT * FROM tbcliente WHERE NOME > 'FERNANDO CAVALCANTE';
SELECT * FROM tbcliente WHERE NOME <> 'FERNANDO CAVALCANTE';
SELECT * FROM tbproduto WHERE PRECO_LISTA = 16.008;
SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;

-- select * from tbproduto WHERE SABOR = 'CITRICUS';
SELECT * FROM tabela_de_vendedores WHERE NOME = 'CLAUDIA MORAIS'
UPDATE TBPRODUTO SET SABOR = 'CITRICUS' WHERE SABOR = 'lIMÃO';
INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00238','Pericles Alves','2016-08-21',0.11,0);
ALTER TABLE TABELA_DE_VENDEDORES ADD PRIMARY KEY (MATRICULA);

CREATE TABLE TABELA_DE_VENDEDORES
( MATRICULA varchar(5),
NOME varchar(100),
PERCENTUAL_COMISSAO float,
DATA_ADMISSAO date,
DE_FERIAS bit);

ALTER TABLE TABELA_DE_VENDEDORES ADD COLUMN (DATA_ADMISSAO DATE);
ALTER TABLE TABELA_DE_VENDEDORES ADD COLUMN (DE_FERIAS  BIT);
INSERT INTO TBCLIENTE (
	CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO,
    LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA )
VALUES (
	'88855577722','JOÃO DA SILVA', 'RUA RPOJETADA A NUMERO 10','G','VILA ROMAN','CARATINGA','AM','22564300','1986-05-29',37,'M',10000,2000,0);
  

ALTER TABLE TBCLIENTE ADD COLUMN (DATA_NASCIMENTO DATE)
ALTER TABLE TBPRODUTO ADD PRIMARY KEY (PRODUTO);
DELETE FROM TBPRODUTO WHERE PRODUTO = '1078680';

UPDATE TBPRODUTO SET EMBALAGEM = 'LATA', PRECO_LISTA = 2.46 WHERE PRODUTO = '544931';
UPDATE TBPRODUTO SET EMBALAGEM = 'GARRAFA' WHERE PRODUTO = '1078680';

UPDATE TABELA_DE_VENDEDORES SET NOME = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233';


INSERT INTO TABELA_DE_VENDEDORES	(MATRICULA, NOME, PERCENTUAL_COMISSAO) VALUES ('00233','João Geraldo da Fonseca',0.10);
INSERT INTO TBPRODUTO(
	PRODUTO, NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES (
	'1004327','Videira do Campo - 1,5 Litros - Melancia','PET','1,5L','Melâcia',19.51);


DROP TABLE 'SCHEMA'.'TABLE'

CREATE TABLE `JUICE`.`tbproduto` (
  `PRODUTO` VARCHAR(20) NULL,
  `NOME` VARCHAR(45) NULL,
  `EMBALAGEM` VARCHAR(45) NULL,
  `TAMANHO` VARCHAR(45) NULL,
  `SABOR` VARCHAR(45) NULL,
  `PRECO_LISTA` FLOAT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE TABELA_DE_VENDEDORES (
	MATRICULA VARCHAR(5),
    NOME VARCHAR(100),
    PERCENTUAL_COMISSAO FLOAT
    )


CREATE TABLE tbcliente
( CPF VARCHAR(11), 
  NOME VARCHAR(100),
  ENDERECO1 VARCHAR(150),
  ENDERECO2 VARCHAR(150),
  BAIRRO VARCHAR(50),
  CIDADE VARCHAR(50),
  ESTADO VARCHAR(50),
  CEP VARCHAR(8),
  IDADE SMALLINT,
  SEXO CHAR(1),
  LIMITE_CREDITO FLOAT,
  VOLUME_COMPRA FLOAT,
  PRIMEIRA_COMPRA BIT(1)
  )
  */
  -- CREATE SCHEMA `juice` DEFAULT CHARACTER SET utf8 ;