/* CREATE DATABASE */
/*
CREATE {DATABASE | SCHEMA} [IF NOT EXISTS] DB_NAME [CREATE_SPECIFICATION]

create_specification:
[DEFAULT] CHARACTER SET [=] charset_name
| [DEFAULT] COLLATE [=] collation_name
| DEFAULT ENCRYPTION [=] {'Y' | 'N'}
*/
/* EXCLUINDO O BANCO DE DADOS */
-- DROP {DATABASE | SCHEMA} [IF EXISTS] DB_NAME