SELECT LTRIM('  OLÁ') AS RESULTADO;
SELECT RTRIM('OLÁ    ') AS RESULTADO;
SELECT TRIM('      OLÁ        ') AS RESULTADO;
SELECT CONCAT('OLÁ',' ', 'TUDO BEM ','?') RSULTADO;
SELECT UPPER('olá, tudo bem?') as RESULTADO;
SELECT LOWER('OLÁ, TUDO BEM?') AS RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?',6) RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?',6,4) RESULTADO;
SELECT CONCAT(NOME,'(',CPF,')') RESULTADO FROM tabela_de_clientes;

-- DESAFIO --
SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS COMPLETO
FROM tabela_de_clientes;
