
SELECT DAYNAME("1986-05-29");
SELECT DATEDIFF("2023-05-29","1986-05-29");
SELECT CURRENT_TIMESTAMP();
SELECT CURDATE();
SELECT CURRENT_TIME();
SELECT ADDDATE("2017-06-15 09:34:21", "2") RESULTADO;
SELECT ADDDATE("2017-06-15", INTERVAL -10 YEAR) RESULTADO;
SELECT SYSDATE() FROM DUAL;
SELECT YEAR(CURRENT_TIMESTAMP());
SELECT MONTH(CURRENT_TIMESTAMP());
SELECT MONTHNAME(CURRENT_TIMESTAMP());
SELECT DATEDIFF('2024-01-01',CURRENT_TIMESTAMP()) RESULTADO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(),'1986-05-29') RESULTADO;
SELECT CURRENT_TIMESTAMP() AS DIA_HOJE, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) RESULTADO;
SELECT DISTINCT DATA_VENDA FROM notas_fiscais;
SELECT DISTINCT DATA_VENDA, DAYNAME(DATA_VENDA) DIA, MONTHNAME(DATA_VENDA) MES,
YEAR(DATA_VENDA) AS ANO FROM notas_fiscais;

-- DESAFIO --- 
SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS    IDADE
FROM  tabela_de_clientes;

