SELECT CURRENT_TIMESTAMP() RESULTADO;
SELECT CONCAT('O DIA DE HOJE É',CURRENT_TIMESTAMP()) RESULTADO;
SELECT CONCAT('O DIA DE HOJE É; ',
DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%Y - %U')) RESULTADO;

SELECT CONVERT(23.3,CHAR) RESULTADO;
SELECT SUBSTRING( CONVERT(23.3,CHAR),1,1) RESULTADO;

-- DESAFIO --
SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CAST(SUM(INF.QUANTIDADE * INF.preco) AS char (20))
 , ' no ano ', CAST(YEAR(NF.DATA_VENDA) AS char (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA);
